### ISSUE TITLE
Click in a name day (select a week) selects previous day

### ISSUE THREAD

**Issue by spock74** [jukkagrao/ng.multidateselect#4]
By clicking in a day name it selects the day immediately before. As shown in the png, wed was clucked but Tue was selected.
![wed-tue](https://cloud.githubusercontent.com/assets/377364/19670684/1206a860-9a48-11e6-959f-69caa77f242e.png)
.

**Comment by jukkagrao** [comment]
I can't reproduce this bug, which value of starting-day do you have and what is your system region?
